parameters:
#    photos_photos.example.class: Garethp\PhotosBundle\Example

services:
#    photos_photos.example:
#        class: %photos_photos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
